### ISSUE TITLE
Modular JAR files created with recent JDK

### ISSUE THREAD

**Issue by sormuras** [sandermak/modulescanner#15]
- Does the scanner support JAR files created with JDK 14 or newer?
- Does it only depend on the JRE that is used to run the scanner on?
- If yes, on which Java version does the scanner run "at Maven Central"?

**Comment by sormuras** [comment]
Modules compiled for Java SE 16 are not supported!

Find some examples here: https://repo.maven.apache.org/maven2/com/github/sormuras/bach/com.github.sormuras.bach/

Those JAR files are not scanned correctly and therefore not written to the CSV files.

**Comment by sormuras** [comment]
I contacted Sonatype to help out by updated in the underlying Java Runtime that executes the `modulescanner` program.

**Comment by sormuras** [comment]
Here's another case with modules targeting Java 15.

https://github.com/sormuras/modules/discussions/18#discussioncomment-480806

**Comment by scherzhaft** [comment]
> I contacted Sonatype to help out by updating the underlying Java Runtime (it's 11 at the moment, iirc) that executes the `modulescanner` program.

I have updated the Maven Central modulescanner env to jdk16.  Going to do a test scan of https://repo.maven.apache.org/maven2/com/github/sormuras/bach/com.github.sormuras.bach/.

**Comment by sormuras** [comment]
Thanks for the update and the heads-up, Shane. As soon as your test is done, I'll trigger an update of the CSV-consuming scanner.

**Comment by scherzhaft** [comment]
> Thanks for the update and the heads-up, Shane. As soon as your test is done, I'll trigger an update of the CSV-consuming scanner.

com.github.sormuras.bach showed up in the csv, should be all set.

**Comment by sormuras** [comment]
So, do I understand it correctly, that the next uploads will be parsed and included in the CSV files, which will then be pushed to the S3 bucket, as usual.

In other words, modules that target Java 12-16 that were uploaded before the update of the environment to JDK 16 are NOT included retrospectively?

**Comment by scherzhaft** [comment]
Correct

**Comment by sormuras** [comment]
![image](https://user-images.githubusercontent.com/2319838/112708868-06d85e00-8eb5-11eb-828f-b1082e8dc2ca.png)

https://github.com/sormuras/modules/commit/595594741b868cecd1f2d01326ff0fde0cc5c6fc

Module `com.github.sormuras.bach` was also propagated to the bucket. Due to your manual test scan, methinks.

**Comment by sormuras** [comment]
Closing this issue for the time being - let's open a new one for JDK 17 in September 2021.
