### ISSUE TITLE
explicit mode?

### ISSUE THREAD

**Issue by scherzhaft** [sandermak/modulescanner#5]
Being able pass a list of files to scan will be very helpful for doing scans, both for scanning the deltas of new releases to Central, and for breaking the initial baseline scan up into several smaller more reasonable scans.

**Comment by sandermak** [comment]
Breaking up the initial baseline scan can be done by running the app on different subdirs in parallel. But I do see the value of also allowing individual files being passed in. These won't have the context of `maven-metadata.xml` then, so we need to deal with that separately from the `MavenRepoWalker` code path.

**Comment by scherzhaft** [comment]
Following the maven G/A/V/*.jar convention would a `dirname G/A/V/*.jar` and/or a double dirname work?

**Comment by scherzhaft** [comment]
Poking around in the code and doing some testing, it looks like I am able to get a 'quazi' explicit mode by specifying the full path to a given maven-metadata.xml as the repo path.

**Comment by sormuras** [comment]
> ... a 'quazi' explicit mode by specifying ...

So, is the status-quo okay for you? If yes, please close this issue.

**Comment by scherzhaft** [comment]
I am currently sending explicit maven-metadata.xml paths to it one at a
time and using xargs -P to speed it up, seems to be working fine that way.
