### ISSUE TITLE
invoking CSV mode

### ISSUE THREAD

**Issue by scherzhaft** [sandermak/modulescanner#6]
I have tried various version of the following and cant seem to get the csv generation to work.

`mvn  exec:java -Dexec.mainClass="org.adoptopenjdk.modulescanner.Main" -Dexec.args="src/test/resources/test-maven-repo 20170101000000 /home/maven/test.csv`

Is the CSV mode suppose to be working in the current version of the source?  If so what is the correct way to invoke it?

**Comment by sormuras** [comment]
Travis CI is happy https://travis-ci.com/sandermak/modulescanner and locally all tests, including https://github.com/sandermak/modulescanner/blob/master/src/test/java/org/adoptopenjdk/modulescanner/MainTest.java, do also work.

Are you sure that you pass two different arguments with `-Dexec.args="src/test/resources/test-maven-repo 20170101000000 /home/maven/test.csv"`?

Is there any exception showing up?

**Comment by sormuras** [comment]
The `main` methods now logs the arguments:

```
9:02:08.514 [main] INFO  Main - Scanning for modules...
19:02:08.514 [main] INFO  Main -   directoryToScan = src\test\resources\test-maven-repo
19:02:08.514 [main] INFO  Main -        cutoffDate = 20170101000000
19:02:08.514 [main] INFO  Main -            output = /usr/tmp/actual-8599239598209794889-modulescanner.csv
```

Hope that helps.

Btw. are you using Java 10 to run the application?

**Comment by scherzhaft** [comment]
Seems to be working now, thanks!
